### ISSUE TITLE
module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by pinkiepi-e** [SociallyIneptWeeb/AICoverGen#38]
Hey there,

After painful local success installation of AICoverGen, I wasn't able to generate anything. When I hit `Converting voice using RVC` I immediately hit error: 

"module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.\nThe aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations"

And there is traceback from console:

```
Traceback (most recent call last):
  File "D:\AICoverGen\src\main.py", line 275, in song_cover_pipeline
    voice_change(voice_model, main_vocals_dereverb_path, ai_vocals_path, pitch_change, f0_method, index_rate, filter_radius, rms_mix_rate, protect, crepe_hop_length, is_webui)
  File "D:\AICoverGen\src\main.py", line 187, in voice_change
    rvc_infer(rvc_index_path, index_rate, vocals_path, output_path, pitch_change, f0_method, cpt, version, net_g, filter_radius, tgt_sr, rms_mix_rate, protect, crepe_hop_length, vc, hubert_model)
  File "D:\AICoverGen\src\rvc.py", line 150, in rvc_infer
    audio_opt = vc.pipeline(hubert_model, net_g, 0, audio, input_path, times, pitch_change, f0_method, index_path, index_rate, if_f0, filter_radius, tgt_sr, 0, rms_mix_rate, version, protect, crepe_hop_length)
  File "D:\AICoverGen\src\vc_infer_pipeline.py", line 549, in pipeline
    pitch, pitchf = self.get_f0(
  File "D:\AICoverGen\src\vc_infer_pipeline.py", line 368, in get_f0
    f0_coarse = np.rint(f0_mel).astype(np.int)
  File "C:\Users\PinkiePie\AppData\Roaming\Python\Python39\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PinkiePie\AppData\Roaming\Python\Python39\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\PinkiePie\AppData\Roaming\Python\Python39\site-packages\gradio\blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "C:\Users\PinkiePie\AppData\Roaming\Python\Python39\site-packages\gradio\blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\PinkiePie\AppData\Roaming\Python\Python39\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\PinkiePie\AppData\Roaming\Python\Python39\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\PinkiePie\AppData\Roaming\Python\Python39\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\PinkiePie\AppData\Roaming\Python\Python39\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "D:\AICoverGen\src\main.py", line 293, in song_cover_pipeline
    raise_exception(str(e), is_webui)
  File "D:\AICoverGen\src\main.py", line 81, in raise_exception
    raise gr.Error(error_msg)
gradio.exceptions.Error: "module 'numpy' has no attribute 'int'.\n`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.\nThe aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations"
2023-08-27 11:39:25 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 500 Internal Server Error"
2023-08-27 11:39:25 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
```

Could be that fixed?

I am using Windows 11, 22621.1413 build with Python 3.9.13.

And I want to do it more locally as I do not support Google Services at all, so I prefer local over cloud. And I have even good GPU (RTX 3070), kinda powerful, so I guess it can run pretty good.

Thanks

**Comment by SociallyIneptWeeb** [comment]
If your current version of numpy is not 1.23.5, you can try pip uninstalling numpy and installing numpy==1.23.5.

**Comment by pinkiepi-e** [comment]
Okay, thank you so much for that tip.

Even though I have to do it like 3 or 4 times and it started to work somehow.

Can be now closed, at it is fixed.
